/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Seguro;
import controlador.Mantenedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Central Gamer
 */

public class Datos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Datos.class.getName());

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opciones = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGeneral = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDetallada = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPorcentaje = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese los datos ");

        jLabel2.setText("Nombre del seguro");

        jLabel3.setText("Descripcion general");

        jLabel4.setText("Descripcion detallada ");

        opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "eliga seguro", "seguro basico", "seguro normal", "seguro premium" }));
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });

        jLabel5.setText("Porcentaje cobertura");

        jButton1.setText("Guardar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtGeneral.setEditable(false);
        jScrollPane1.setViewportView(txtGeneral);

        TxtDetallada.setEditable(false);
        jScrollPane2.setViewportView(TxtDetallada);

        txtPorcentaje.setEditable(false);
        jScrollPane3.setViewportView(txtPorcentaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        // TODO add your handling code here:
        String seleccionado = opciones.getSelectedItem().toString();

        if (seleccionado.equalsIgnoreCase("seguro basico")) {
            txtGeneral.setText("Plan de protección médica esencial pensado para cubrir únicamente las atenciones más básicas y necesarias, ofreciendo un nivel de seguridad mínimo a bajo costo.");
            TxtDetallada.setText("Este plan brinda acceso a consultas generales, algunos exámenes básicos, atención ambulatoria simple, medicamentos esenciales y urgencias limitadas. Está diseñado para personas que requieren un servicio fundamental sin grandes prestaciones adicionales.");
            txtPorcentaje.setText("50%");
        }
        if (seleccionado.equalsIgnoreCase("seguro normal")) {
            txtGeneral.setText("Plan de cobertura equilibrada que amplía los servicios del nivel básico y ofrece acceso a especialistas y prestaciones de mayor complejidad.");
            TxtDetallada.setText("Permite acceder a consultas especializadas, exámenes avanzados, hospitalización ambulatoria, tratamientos médicos de mediana complejidad y atención de urgencias con una cobertura más amplia. Está estructurado para usuarios que buscan buena relación entre costo y beneficios médicos.");
            txtPorcentaje.setText("75%");
        }
        if (seleccionado.equalsIgnoreCase("seguro premium")) {
            txtGeneral.setText("Plan de alta cobertura diseñado para entregar prácticamente la totalidad de los servicios médicos con acceso preferente y prestaciones avanzadas.");
            TxtDetallada.setText("Incluye atención completa en consultas, hospitalización, cirugías, exámenes de alta complejidad, medicamentos ampliados, programas preventivos y servicios médicos avanzados. Se orienta a quienes buscan la máxima protección disponible y el mínimo gasto en salud.");
            txtPorcentaje.setText("100%");
        }

    }//GEN-LAST:event_opcionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String seguroseleccionado = (String) opciones.getSelectedItem();
        String general1 = "Plan de protección médica esencial pensado para cubrir únicamente las atenciones más básicas y necesarias, ofreciendo un nivel de seguridad mínimo a bajo costo.";
        String especifico1 = "Este plan brinda acceso a consultas generales, algunos exámenes básicos, atención ambulatoria simple, medicamentos esenciales y urgencias limitadas. Está diseñado para personas que requieren un servicio fundamental sin grandes prestaciones adicionales.";
        double porc1 = 50;
        String general2 = "Plan de cobertura equilibrada que amplía los servicios del nivel básico y ofrece acceso a especialistas y prestaciones de mayor complejidad.";
        String especifico2 = "Permite acceder a consultas especializadas, exámenes avanzados, hospitalización ambulatoria, tratamientos médicos de mediana complejidad y atención de urgencias con una cobertura más amplia. Está estructurado para usuarios que buscan buena relación entre costo y beneficios médicos.";
        double porc2 = 75;
        String general3 = "Plan de alta cobertura diseñado para entregar prácticamente la totalidad de los servicios médicos con acceso preferente y prestaciones avanzadas.";
        String especifico3 = "Incluye atención completa en consultas, hospitalización, cirugías, exámenes de alta complejidad, medicamentos ampliados, programas preventivos y servicios médicos avanzados. Se orienta a quienes buscan la máxima protección disponible y el mínimo gasto en salud.";
        double porc3 = 100;
        String opcion = (String) opciones.getSelectedItem();
        Seguro nuevoSeguro = null;

        switch (opcion) {
            case "seguro basico":
                nuevoSeguro = new Seguro(-1, seguroseleccionado, general1, especifico1, porc1);
                break;
            case "seguro normal":
                nuevoSeguro = new Seguro(-1, seguroseleccionado, general2, especifico2, porc2);
                break;
            case "seguro premium":
                nuevoSeguro = new Seguro(-1, seguroseleccionado, general3, especifico3, porc3);
                break;
        }

        if (nuevoSeguro != null) {
            Mantenedor mant = new Mantenedor();
            mant.agregarProducto(nuevoSeguro);
        }
        JOptionPane.showMessageDialog(this,
                "Producto guardado exitosamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
    }


    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TxtDetallada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JTextPane txtGeneral;
    private javax.swing.JTextPane txtPorcentaje;
    // End of variables declaration//GEN-END:variables

